version: '3'

services:
  smirror:
    image: roschaefer/smirror
    build: .
    ports:
      - 8080:8080
    environment:
      - HOST=0.0.0.0
      - TRANSIT_API_KEY=${TRANSIT_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - STOCKS_API_KEY=${STOCKS_API_KEY}

  mqtt:
    image: ncarlier/mqtt
    ports:
      - 1883:1883
